language: julia

os:
  - linux
  - osx
  - windows

julia:
  - 1.0
  - 1.4
  - nightly

matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true

notifications:
  email: false

codecov: true
