name = "UnicodeGraphics"
uuid = "ebadf6b4-db70-5817-83da-4a19ad584e34"
authors = ["Rafael Schouten <rafaelschouten@gmail.com>"]
version = "0.1.2"

[compat]
julia = "1"

[extras]
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["OffsetArrays", "Test"]
